language: php

php:
  - 5.3

sudo: false

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

before_script:
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - vendor/bin/phpunit tests/
