language: php

php:
  - 5.3

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction

before_script:
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - vendor/bin/phpunit --exclude-group ignore tests/ApiWrapperTest.php
