sudo: false
language: php

php:
  - '5.3'

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction
  - phpenv rehash

before_script:
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpcs --standard=PSR2 src/ || true
  - ./vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls
