api:
    env:
        prod: https://api.oyst.com
        sandbox: https://api.sandbox.oyst.eu
    path:
        catalog: /catalog
        order: /order
        payment: /payment
        oneclick: /oneclick
