api:
  env:
    prod: https://api-gw.oyst.com
    sandbox: https://api-gw.sandbox.oyst.eu
  path:
    catalog: /oneclick-api/merchants
    order: /oneclick-api/merchants
    payment: /oneclick-api
    oneclick: /oneclick-api
