api:
    url:
        preprod:
            catalog: https://api.staging.oyst.eu/catalog
            order: https://api.staging.oyst.eu/order
            payment: https://api.staging.oyst.eu/payment
            oneclick: https://api.staging.oyst.eu/oneclick
        prod:
            catalog: https://api.oyst.com/catalog
            order: https://api.oyst.com/oneclick/order
            payment: https://api.oyst.com/payment
            oneclick: https://api.oyst.com/oneclick
        test:
            catalog: https://localhost/catalog
            order: https://localhost/order
            payment: https://localhost/payment
            oneclick: https://localhost/oneclick
